version: '3.8'
services:
  timetracking-bot:
    container_name: timetracking-bot.local
    build:
      context: .
    environment:
      - TIMETRACKING_TG_TOKEN=${TIMETRACKING_TG_TOKEN}
    volumes:
      - timetracking-data:/data
    restart: always

volumes:
  timetracking-data:
