name: Create and publish a Docker image

on:
  push:
    branches: ['develop']

env:
  REGISTRY: ghcr.io
  CONTAINER_NAME: ${{ github.event.repository.name }}-dev
  VOLUME_NAME: ${{ github.event.repository.name }}-data-dev

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: lowercase github.repository
        run: |
          echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: lowercase github.repository
        run: |
          echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EDU_PRACTICE_HOST }}
          username: ${{ secrets.EDU_PRACTICE_USERNAME }}
          key: ${{ secrets.EDU_PRACTICE_SSH_KEY }}
          port: ${{ secrets.EDU_PRACTICE_SSH_PORT }}
          script: |
            docker logout;
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev;
            docker volume create ${{ env.VOLUME_NAME }};
            docker rm -f ${{ env.CONTAINER_NAME }} || true;
            docker run -d \
              -v ${{ env.CONTAINER_NAME }}:/app/data/ \
              -e TIMETRACKING_TG_TOKEN="${{ secrets.TIMETRACKING_TG_TOKEN }}" \
              --name ${{ env.CONTAINER_NAME }} \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev;
